/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as OrdenesRouteImport } from './routes/ordenes'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TiendasRouteImport } from './routes/tiendas'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as AdminAyudaRouteImport } from './routes/admin/ayuda'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as CategoriasCategoriaSlugRouteImport } from './routes/categorias.$categoriaSlug'
import { Route as DeliveryIdRouteImport } from './routes/delivery.$id'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosProductoIdRouteImport } from './routes/productos.$productoId'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosServicioIdRouteImport } from './routes/servicios.$servicioId'
import { Route as TiendasIndexRouteImport } from './routes/tiendas.index'
import { Route as TiendasTiendaIdRouteImport } from './routes/tiendas.$tiendaId'
import { Route as VehiculosIdRouteImport } from './routes/vehiculos.$id'
import { Route as AdminStoresStoreIdRouteImport } from './routes/admin/stores/$storeId'
import { Route as ApiWhatsappAvisarRouteImport } from './routes/api/whatsapp.avisar'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesRoute = OrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasRoute = TiendasRouteImport.update({
  id: '/tiendas',
  path: '/tiendas',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAyudaRoute = AdminAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriasCategoriaSlugRoute = CategoriasCategoriaSlugRouteImport.update({
  id: '/$categoriaSlug',
  path: '/$categoriaSlug',
  getParentRoute: () => CategoriasRoute,
} as any)
const DeliveryIdRoute = DeliveryIdRouteImport.update({
  id: '/delivery/$id',
  path: '/delivery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductoIdRoute = ProductosProductoIdRouteImport.update({
  id: '/productos/$productoId',
  path: '/productos/$productoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosServicioIdRoute = ServiciosServicioIdRouteImport.update({
  id: '/$servicioId',
  path: '/$servicioId',
  getParentRoute: () => ServiciosRoute,
} as any)
const TiendasIndexRoute = TiendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TiendasRoute,
} as any)
const TiendasTiendaIdRoute = TiendasTiendaIdRouteImport.update({
  id: '/$tiendaId',
  path: '/$tiendaId',
  getParentRoute: () => TiendasRoute,
} as any)
const VehiculosIdRoute = VehiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehiculosRoute,
} as any)
const AdminStoresStoreIdRoute = AdminStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWhatsappAvisarRoute = ApiWhatsappAvisarRouteImport.update({
  id: '/api/whatsapp/avisar',
  path: '/api/whatsapp/avisar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/ordenes': typeof OrdenesRoute
  '/publicar': typeof PublicarRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tiendas': typeof TiendasRouteWithChildren
  '/vehiculos': typeof VehiculosRouteWithChildren
  '/vender': typeof VenderRoute
  '/admin/ayuda': typeof AdminAyudaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/support': typeof AdminSupportRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/vehiculos/$id': typeof VehiculosIdRoute
  '/legal/': typeof LegalIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/tiendas/': typeof TiendasIndexRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/whatsapp/avisar': typeof ApiWhatsappAvisarRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/ordenes': typeof OrdenesRoute
  '/publicar': typeof PublicarRoute
  '/vehiculos': typeof VehiculosRouteWithChildren
  '/vender': typeof VenderRoute
  '/admin/ayuda': typeof AdminAyudaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/support': typeof AdminSupportRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/vehiculos/$id': typeof VehiculosIdRoute
  '/legal': typeof LegalIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/tiendas': typeof TiendasIndexRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/whatsapp/avisar': typeof ApiWhatsappAvisarRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/ordenes': typeof OrdenesRoute
  '/publicar': typeof PublicarRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/tiendas': typeof TiendasRouteWithChildren
  '/vehiculos': typeof VehiculosRouteWithChildren
  '/vender': typeof VenderRoute
  '/admin/ayuda': typeof AdminAyudaRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/support': typeof AdminSupportRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/vehiculos/$id': typeof VehiculosIdRoute
  '/legal/': typeof LegalIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/tiendas/': typeof TiendasIndexRoute
  '/admin/stores/$storeId': typeof AdminStoresStoreIdRoute
  '/api/whatsapp/avisar': typeof ApiWhatsappAvisarRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/dashboard'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/ordenes'
    | '/publicar'
    | '/servicios'
    | '/tiendas'
    | '/vehiculos'
    | '/vender'
    | '/admin/ayuda'
    | '/admin/chat'
    | '/admin/crm'
    | '/admin/support'
    | '/categorias/$categoriaSlug'
    | '/delivery/$id'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/vehiculos/$id'
    | '/legal/'
    | '/productos/'
    | '/servicios/'
    | '/tiendas/'
    | '/admin/stores/$storeId'
    | '/api/whatsapp/avisar'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/dashboard'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/ordenes'
    | '/publicar'
    | '/vehiculos'
    | '/vender'
    | '/admin/ayuda'
    | '/admin/chat'
    | '/admin/crm'
    | '/admin/support'
    | '/categorias/$categoriaSlug'
    | '/delivery/$id'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/vehiculos/$id'
    | '/legal'
    | '/productos'
    | '/servicios'
    | '/tiendas'
    | '/admin/stores/$storeId'
    | '/api/whatsapp/avisar'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/dashboard'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/ordenes'
    | '/publicar'
    | '/servicios'
    | '/tiendas'
    | '/vehiculos'
    | '/vender'
    | '/admin/ayuda'
    | '/admin/chat'
    | '/admin/crm'
    | '/admin/support'
    | '/categorias/$categoriaSlug'
    | '/delivery/$id'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/vehiculos/$id'
    | '/legal/'
    | '/productos/'
    | '/servicios/'
    | '/tiendas/'
    | '/admin/stores/$storeId'
    | '/api/whatsapp/avisar'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AyudaRoute: typeof AyudaRoute
  BuscarRoute: typeof BuscarRoute
  CarritoRoute: typeof CarritoRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CuentaRoute: typeof CuentaRoute
  DashboardRoute: typeof DashboardRoute
  FavoritosRoute: typeof FavoritosRoute
  MensajesRoute: typeof MensajesRoute
  OfertasRoute: typeof OfertasRoute
  OrdenesRoute: typeof OrdenesRoute
  PublicarRoute: typeof PublicarRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  TiendasRoute: typeof TiendasRouteWithChildren
  VehiculosRoute: typeof VehiculosRouteWithChildren
  VenderRoute: typeof VenderRoute
  DeliveryIdRoute: typeof DeliveryIdRoute
  LegalDocRoute: typeof LegalDocRoute
  ProductosProductoIdRoute: typeof ProductosProductoIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ApiWhatsappAvisarRoute: typeof ApiWhatsappAvisarRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordenes': {
      id: '/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof OrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas': {
      id: '/tiendas'
      path: '/tiendas'
      fullPath: '/tiendas'
      preLoaderRoute: typeof TiendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ayuda': {
      id: '/admin/ayuda'
      path: '/ayuda'
      fullPath: '/admin/ayuda'
      preLoaderRoute: typeof AdminAyudaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categorias/$categoriaSlug': {
      id: '/categorias/$categoriaSlug'
      path: '/$categoriaSlug'
      fullPath: '/categorias/$categoriaSlug'
      preLoaderRoute: typeof CategoriasCategoriaSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/delivery/$id': {
      id: '/delivery/$id'
      path: '/delivery/$id'
      fullPath: '/delivery/$id'
      preLoaderRoute: typeof DeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productoId': {
      id: '/productos/$productoId'
      path: '/productos/$productoId'
      fullPath: '/productos/$productoId'
      preLoaderRoute: typeof ProductosProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/$servicioId': {
      id: '/servicios/$servicioId'
      path: '/$servicioId'
      fullPath: '/servicios/$servicioId'
      preLoaderRoute: typeof ServiciosServicioIdRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/tiendas/': {
      id: '/tiendas/'
      path: '/'
      fullPath: '/tiendas/'
      preLoaderRoute: typeof TiendasIndexRouteImport
      parentRoute: typeof TiendasRoute
    }
    '/tiendas/$tiendaId': {
      id: '/tiendas/$tiendaId'
      path: '/$tiendaId'
      fullPath: '/tiendas/$tiendaId'
      preLoaderRoute: typeof TiendasTiendaIdRouteImport
      parentRoute: typeof TiendasRoute
    }
    '/vehiculos/$id': {
      id: '/vehiculos/$id'
      path: '/$id'
      fullPath: '/vehiculos/$id'
      preLoaderRoute: typeof VehiculosIdRouteImport
      parentRoute: typeof VehiculosRoute
    }
    '/admin/stores/$storeId': {
      id: '/admin/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/admin/stores/$storeId'
      preLoaderRoute: typeof AdminStoresStoreIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/whatsapp/avisar': {
      id: '/api/whatsapp/avisar'
      path: '/api/whatsapp/avisar'
      fullPath: '/api/whatsapp/avisar'
      preLoaderRoute: typeof ApiWhatsappAvisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAyudaRoute: typeof AdminAyudaRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminStoresStoreIdRoute: typeof AdminStoresStoreIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAyudaRoute: AdminAyudaRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminStoresStoreIdRoute: AdminStoresStoreIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategoriasRouteChildren {
  CategoriasCategoriaSlugRoute: typeof CategoriasCategoriaSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasCategoriaSlugRoute: CategoriasCategoriaSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ServiciosRouteChildren {
  ServiciosServicioIdRoute: typeof ServiciosServicioIdRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosServicioIdRoute: ServiciosServicioIdRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

interface TiendasRouteChildren {
  TiendasTiendaIdRoute: typeof TiendasTiendaIdRoute
  TiendasIndexRoute: typeof TiendasIndexRoute
}

const TiendasRouteChildren: TiendasRouteChildren = {
  TiendasTiendaIdRoute: TiendasTiendaIdRoute,
  TiendasIndexRoute: TiendasIndexRoute,
}

const TiendasRouteWithChildren =
  TiendasRoute._addFileChildren(TiendasRouteChildren)

interface VehiculosRouteChildren {
  VehiculosIdRoute: typeof VehiculosIdRoute
}

const VehiculosRouteChildren: VehiculosRouteChildren = {
  VehiculosIdRoute: VehiculosIdRoute,
}

const VehiculosRouteWithChildren = VehiculosRoute._addFileChildren(
  VehiculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AyudaRoute: AyudaRoute,
  BuscarRoute: BuscarRoute,
  CarritoRoute: CarritoRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CuentaRoute: CuentaRoute,
  DashboardRoute: DashboardRoute,
  FavoritosRoute: FavoritosRoute,
  MensajesRoute: MensajesRoute,
  OfertasRoute: OfertasRoute,
  OrdenesRoute: OrdenesRoute,
  PublicarRoute: PublicarRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  TiendasRoute: TiendasRouteWithChildren,
  VehiculosRoute: VehiculosRouteWithChildren,
  VenderRoute: VenderRoute,
  DeliveryIdRoute: DeliveryIdRoute,
  LegalDocRoute: LegalDocRoute,
  ProductosProductoIdRoute: ProductosProductoIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ApiWhatsappAvisarRoute: ApiWhatsappAvisarRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
