/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as CategoriasCategoriaSlugRouteImport } from './routes/categorias.$categoriaSlug'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosProductoIdRouteImport } from './routes/productos.$productoId'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosServicioIdRouteImport } from './routes/servicios.$servicioId'
import { Route as TiendasIndexRouteImport } from './routes/tiendas.index'
import { Route as TiendasTiendaIdRouteImport } from './routes/tiendas.$tiendaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasCategoriaSlugRoute = CategoriasCategoriaSlugRouteImport.update({
  id: '/$categoriaSlug',
  path: '/$categoriaSlug',
  getParentRoute: () => CategoriasRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductoIdRoute = ProductosProductoIdRouteImport.update({
  id: '/productos/$productoId',
  path: '/productos/$productoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosServicioIdRoute = ServiciosServicioIdRouteImport.update({
  id: '/servicios/$servicioId',
  path: '/servicios/$servicioId',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasIndexRoute = TiendasIndexRouteImport.update({
  id: '/tiendas/',
  path: '/tiendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasTiendaIdRoute = TiendasTiendaIdRouteImport.update({
  id: '/tiendas/$tiendaId',
  path: '/tiendas/$tiendaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/publicar': typeof PublicarRoute
  '/vender': typeof VenderRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/legal/': typeof LegalIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/tiendas/': typeof TiendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/publicar': typeof PublicarRoute
  '/vender': typeof VenderRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/legal': typeof LegalIndexRoute
  '/productos': typeof ProductosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/tiendas': typeof TiendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/carrito': typeof CarritoRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/mensajes': typeof MensajesRoute
  '/ofertas': typeof OfertasRoute
  '/publicar': typeof PublicarRoute
  '/vender': typeof VenderRoute
  '/categorias/$categoriaSlug': typeof CategoriasCategoriaSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/productos/$productoId': typeof ProductosProductoIdRoute
  '/servicios/$servicioId': typeof ServiciosServicioIdRoute
  '/tiendas/$tiendaId': typeof TiendasTiendaIdRoute
  '/legal/': typeof LegalIndexRoute
  '/productos/': typeof ProductosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/tiendas/': typeof TiendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/publicar'
    | '/vender'
    | '/categorias/$categoriaSlug'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/legal/'
    | '/productos/'
    | '/servicios/'
    | '/tiendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/publicar'
    | '/vender'
    | '/categorias/$categoriaSlug'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/legal'
    | '/productos'
    | '/servicios'
    | '/tiendas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/ayuda'
    | '/buscar'
    | '/carrito'
    | '/categorias'
    | '/checkout'
    | '/cuenta'
    | '/favoritos'
    | '/mensajes'
    | '/ofertas'
    | '/publicar'
    | '/vender'
    | '/categorias/$categoriaSlug'
    | '/legal/$doc'
    | '/productos/$productoId'
    | '/servicios/$servicioId'
    | '/tiendas/$tiendaId'
    | '/legal/'
    | '/productos/'
    | '/servicios/'
    | '/tiendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  AyudaRoute: typeof AyudaRoute
  BuscarRoute: typeof BuscarRoute
  CarritoRoute: typeof CarritoRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CuentaRoute: typeof CuentaRoute
  FavoritosRoute: typeof FavoritosRoute
  MensajesRoute: typeof MensajesRoute
  OfertasRoute: typeof OfertasRoute
  PublicarRoute: typeof PublicarRoute
  VenderRoute: typeof VenderRoute
  LegalDocRoute: typeof LegalDocRoute
  ProductosProductoIdRoute: typeof ProductosProductoIdRoute
  ServiciosServicioIdRoute: typeof ServiciosServicioIdRoute
  TiendasTiendaIdRoute: typeof TiendasTiendaIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
  TiendasIndexRoute: typeof TiendasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$categoriaSlug': {
      id: '/categorias/$categoriaSlug'
      path: '/$categoriaSlug'
      fullPath: '/categorias/$categoriaSlug'
      preLoaderRoute: typeof CategoriasCategoriaSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productoId': {
      id: '/productos/$productoId'
      path: '/productos/$productoId'
      fullPath: '/productos/$productoId'
      preLoaderRoute: typeof ProductosProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$servicioId': {
      id: '/servicios/$servicioId'
      path: '/servicios/$servicioId'
      fullPath: '/servicios/$servicioId'
      preLoaderRoute: typeof ServiciosServicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas/': {
      id: '/tiendas/'
      path: '/tiendas'
      fullPath: '/tiendas/'
      preLoaderRoute: typeof TiendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas/$tiendaId': {
      id: '/tiendas/$tiendaId'
      path: '/tiendas/$tiendaId'
      fullPath: '/tiendas/$tiendaId'
      preLoaderRoute: typeof TiendasTiendaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasCategoriaSlugRoute: typeof CategoriasCategoriaSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasCategoriaSlugRoute: CategoriasCategoriaSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  AyudaRoute: AyudaRoute,
  BuscarRoute: BuscarRoute,
  CarritoRoute: CarritoRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CuentaRoute: CuentaRoute,
  FavoritosRoute: FavoritosRoute,
  MensajesRoute: MensajesRoute,
  OfertasRoute: OfertasRoute,
  PublicarRoute: PublicarRoute,
  VenderRoute: VenderRoute,
  LegalDocRoute: LegalDocRoute,
  ProductosProductoIdRoute: ProductosProductoIdRoute,
  ServiciosServicioIdRoute: ServiciosServicioIdRoute,
  TiendasTiendaIdRoute: TiendasTiendaIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  ProductosIndexRoute: ProductosIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
  TiendasIndexRoute: TiendasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
